version: '3'

services:
  java1:
    build: ./Docker
  java2:
    build: ./multi
  java3:
    build: ./shell
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8085:8080
  web:
    image: tomcat
    ports:
      - 8082:8080
